version: "3.9"

services:
  local-db:
    image: mysql:8.0.28-oracle
    container_name: mgl-auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mgl-auth-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: